### ISSUE TITLE
URL format change is causing a 403 when attempting to install MongoDB using m

### ISSUE THREAD

**Issue by shannonbradshaw** [mongodb-js/version-manager#146]
m appears to be looking for urls formatted as follows:
    https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.1.3.tgz
but I believe the format should be:
    https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.1.3.tgz

See below for sample error output

m use 4.1.3
{ HTTPError: Response code 403 (Forbidden)
    at EventEmitter.ee.on.res (/Users/shannon/.nvm/versions/node/v7.4.0/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Immediate.setImmediate (/Users/shannon/.nvm/versions/node/v7.4.0/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  name: 'HTTPError',
  host: 'fastdl.mongodb.org',
  hostname: 'fastdl.mongodb.org',
  method: 'GET',
  path: '/osx/mongodb-osx-ssl-x86_64-4.1.3.tgz',
  protocol: 'https:',
  url: 'https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.1.3.tgz',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: 
   { 'content-type': 'application/xml',
     'transfer-encoding': 'chunked',
     connection: 'close',
     date: 'Wed, 10 Oct 2018 17:34:36 GMT',
     server: 'AmazonS3',
     'x-cache': 'Error from cloudfront',
     via: '1.1 3da3508da5df5956549a94ec250a7674.cloudfront.net (CloudFront)',
     'x-amz-cf-id': '0Y8QO5bPJLJZwjq3uBAquR0c9W0BNy3bkaRysI8svtyAhWd28XzcXw==' } }
✖  Error: Response code 403 (Forbidden)
We apologize for this issue and welcome your bug reports.
Please visit: https://github.com/mongodb-js/version-manager/issues

Try running your command again with debugging on:
   m use --debug

Stack Trace
   HTTPError: Response code 403 (Forbidden)
       at EventEmitter.ee.on.res (/Users/shannon/.nvm/versions/node/v7.4.0/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
       at emitOne (events.js:96:13)
       at EventEmitter.emit (events.js:188:7)
       at Immediate.setImmediate (/Users/shannon/.nvm/versions/node/v7.4.0/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
       at runCallback (timers.js:651:20)
       at tryOnImmediate (timers.js:624:5)
       at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by imlucas** [comment]
Root cause: 
https://github.com/mongodb/mongo/commit/7a91835a9c6c4a20102acf9fb633439223eec556
