### ISSUE TITLE
403 Response when running `m use`

### ISSUE THREAD

**Issue by JacksonBates** [mongodb-js/version-manager#147]
Possibly related to #146?

I've installed the @latest package but still get a 403 when attempting `m use 3.6.8`

Terminal output:
```
{ HTTPError: Response code 403 (Forbidden)
    at EventEmitter.ee.on.res (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Immediate.setImmediate [as _onImmediate] (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  name: 'HTTPError',
  host: 'fastdl.mongodb.org',
  hostname: 'fastdl.mongodb.org',
  method: 'GET',
  path: '/osx/mongodb-macos-x86_64-3.6.8.tgz',
  protocol: 'https:',
  url: 'https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-3.6.8.tgz',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers:
   { 'content-type': 'application/xml',
     'transfer-encoding': 'chunked',
     connection: 'close',
     date: 'Fri, 12 Oct 2018 06:17:49 GMT',
     server: 'AmazonS3',
     'x-cache': 'Error from cloudfront',
     via: '1.1 62b57aad96f95c086d713d3c9a7e766a.cloudfront.net (CloudFront)',
     'x-amz-cf-id': 'Jb6kO_wAQQ7moo12Lb3pRZ565FT3plVOpg8qB1_8UANk3Mrc82cAAA==' } }
✖  Error: Response code 403 (Forbidden)
We apologize for this issue and welcome your bug reports.
Please visit: https://github.com/mongodb-js/version-manager/issues

Try running your command again with debugging on:
   m use --debug

Stack Trace
   HTTPError: Response code 403 (Forbidden)
       at EventEmitter.ee.on.res (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
       at emitOne (events.js:116:13)
       at EventEmitter.emit (events.js:211:7)
       at Immediate.setImmediate [as _onImmediate] (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
       at runCallback (timers.js:810:20)
       at tryOnImmediate (timers.js:768:5)
       at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by cordonrd** [comment]
I'm getting the same error

**Comment by acinader** [comment]
```
MONGODB_VERSION=3.6.5  mongodb-runner start
....
Starting a MongoDB deployment to test against...{ HTTPError: Response code 403 (Forbidden)
    at EventEmitter.ee.on.res (/Users/arthur/code/glow-cloud/node_modules/got/index.js:250:24)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Immediate.setImmediate [as _onImmediate] (/Users/arthur/code/glow-cloud/node_modules/got/index.js:99:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  name: 'HTTPError',
  host: 'fastdl.mongodb.org',
  hostname: 'fastdl.mongodb.org',
  method: 'GET',
  path: '/osx/mongodb-macos-x86_64-3.6.5.tgz',
  protocol: 'https:',
  url: 'https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-3.6.5.tgz',
```
