### ISSUE TITLE
Unable to decompress the downloaded mongo version

### ISSUE THREAD

**Issue by SgtPooki** [mongodb-js/version-manager#15]
D:\code\PROJECT (develop)
λ m 2.4.x

  Downloading MongoDB v2.4.13 [========================================] 100% 0.0sec

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:296:17)

D:\code\PROJECT  (develop)
λ mongo --version
MongoDB shell version: 2.6.7

D:\code\PROJECT  (develop)
λ mongod --version
db version v2.6.7
2015-02-26T12:43:47.699-0600 git version: a7d57ad27c382de82e9cb93bf983a80fd9ac9899

D:\code\PROJECT  (develop)
λ m 2.4.6

  Downloading MongoDB v2.4.6 [========================================] 100% 0.0sec

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:296:17)

**Comment by imlucas** [comment]
@SgtPooki thanks for the report.  mind running that again with debug output?  Looks like it's not getting the correct tarball URL.

```
DEBUG=* m 2.4.x;
```

**Comment by SgtPooki** [comment]
Yea I sure can. But you're correct it's not getting the tarball, it's getting a zip :), an important thing to note here is that I am on windows 8.1. Running again with debug.

**Comment by SgtPooki** [comment]
```
D:\code
λ set DEBUG=mvm::extract & m 2.4.6

  Downloading MongoDB v2.4.6 [========================================] 100% 0.0sec


  mvm::extract reading ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +0ms
  mvm::extract untar-ing.... +2ms
  mvm::extract removed ~\.mongodb\versions\mongodb\2.4.6 +2ms
  mvm::extract removed bad tarball ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +1ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:296:17)
```

**Comment by SgtPooki** [comment]
@imlucas Want me to test that out? Do you have a windows machine to test on?

**Comment by imlucas** [comment]
@SgtPooki would be awesome if you could test!  setup appveyor but it's been running for 22 minutes with no build output :/ https://ci.appveyor.com/project/imlucas/mongodb-version-manager

**Comment by SgtPooki** [comment]
I see that appveyor is running now, but I've got the repo and am testing on that commit now as well.

**Comment by SgtPooki** [comment]
```
D:\code\mongodb-version-manager ((detached from f027d27))
λ SET DEBUG=mvm::extract & node bin\m.js 2.4.6

  Downloading MongoDB v2.4.6 [========================================] 100% 0.0sec


  mvm::extract reading ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +0ms
  mvm::extract removed ~\.mongodb\versions\mongodb\2.4.6 +6ms
  mvm::extract removed bad archive ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +1ms

D:\code\mongodb-version-manager ((detached from f027d27))
λ node bin\m.js ls
0 versions installed.  Run one of:
[Error: Missing required paramater `distro`]

D:\code\mongodb-version-manager\bin\m.js:117
  console.log('    m use stable; # installs MongoDB v' + data.stable.version);
                                                                    ^
TypeError: Cannot read property 'version' of undefined
    at D:\code\mongodb-version-manager\bin\m.js:117:75
    at D:\code\mongodb-version-manager\node_modules\async\lib\async.js:592:17
    at done (D:\code\mongodb-version-manager\node_modules\async\lib\async.js:129:15)
    at D:\code\mongodb-version-manager\node_modules\async\lib\async.js:32:16
    at D:\code\mongodb-version-manager\node_modules\async\lib\async.js:589:21
    at mci (D:\code\mongodb-version-manager\lib\resolve.js:75:12)
    at module.exports (D:\code\mongodb-version-manager\lib\resolve.js:47:12)
    at D:\code\mongodb-version-manager\node_modules\async\lib\async.js:583:25
    at D:\code\mongodb-version-manager\node_modules\async\lib\async.js:125:13
    at Array.forEach (native)

```

**Comment by imlucas** [comment]
@SgtPooki ah excellent.  thanks!  now that appveyor is working, getting in some more tests.

**Comment by imlucas** [comment]
@SgtPooki k appveyor now passing.  `Cannot read property 'version' of undefined` above fixed.  Mind pulling latest and giving it a shot?  if thats good will rev version and publish to npm.

**Comment by SgtPooki** [comment]
Yep, I will do that right now, thanks a ton for the quick work on this :+1:

**Comment by SgtPooki** [comment]
It still does not like the zip.
```
D:\code\mongodb-version-manager ((detached from 4631067))
λ cd ..

D:\code
λ npm install -g mongodb-version-manager\
C:\Users\SgtPooki\AppData\Roaming\npm\m -> C:\Users\SgtPooki\AppData\Roaming\npm\node_modules\mongodb-version-manager\bin\m.js
mongodb-version-manager@0.7.0 C:\Users\SgtPooki\AppData\Roaming\npm\node_modules\mongodb-version-manager
├── which@1.0.9
├── progress@1.1.8
├── underscore@1.7.0
├── async@0.9.0
├── untildify@1.0.0 (user-home@1.1.1)
├── docopt@0.4.1
├── debug@1.0.4 (ms@0.6.2)
├── tildify@1.0.0 (user-home@1.1.1)
├── semver@3.0.1
├── fs-extra@0.10.0 (jsonfile@1.2.0, rimraf@2.2.8, ncp@0.5.1, mkdirp@0.5.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.7, fstream@1.0.4)
├── unzip@0.1.11 (setimmediate@1.0.2, pullstream@0.4.1, readable-stream@1.0.33, match-stream@0.0.2, binary@0.3.0, fstream@0.1.31)
├── request@2.40.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.0, qs@1.0.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
├── cheerio@0.17.0 (dom-serializer@0.0.1, entities@1.1.1, htmlparser2@3.7.3, CSSselect@0.4.1, lodash@2.4.1)
└── downcache@0.0.5-a (graceful-fs@2.0.3, mkdirp@0.3.5, npmlog@1.1.0, request@2.34.0)

D:\code
λ m
0 versions installed.  Run one of:
    m use stable; # installs MongoDB v2.6.8
    m use unstable; # installs MongoDB v3.0.0-rc9

D:\code
λ m use 2.4.6

  Downloading MongoDB v2.4.6 [========================================] 100% 0.0sec


  mvm::extract reading ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +0ms
  mvm::extract removed ~\.mongodb\versions\mongodb\2.4.6 +7ms
  mvm::extract removed bad archive ~\.mongodb\versions\.artifacts\mongodb-win32-x86_64-2.4.6.zip +3ms
```

**Comment by imlucas** [comment]
fixed
