### ISSUE TITLE
Error: Installation failed for Mongodb Version 4.2.2.  Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by byteshiva** [mongodb-js/version-manager#168]
Error: Installation failed for Mongodb Version 4.2.2.  Response code 403 (Forbidden)

Detailed log 
```
StdError [HTTPError]: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/home/xyz/.asdf/installs/nodejs/13.5.0/.npm/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
    at EventEmitter.emit (events.js:305:20)
    at Immediate.<anonymous> (/home/xyz/.asdf/installs/nodejs/13.5.0/.npm/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
    at processImmediate (internal/timers.js:445:21) {
  name: 'HTTPError',
  host: 'fastdl.mongodb.org',
  hostname: 'fastdl.mongodb.org',
  method: 'GET',
  path: '/linux/mongodb-linux-x86_64-ubuntu1910-4.2.3.tgz',
  protocol: 'https:',
  url: 'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1910-4.2.3.tgz',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: {
    'content-type': 'application/xml',
    'transfer-encoding': 'chunked',
    connection: 'close',
    date: 'Sat, 25 Jan 2020 12:43:52 GMT',
    server: 'AmazonS3',
    'x-cache': 'Error from cloudfront',
    via: '1.1 31f93e066d316be54f430c26d6b46c17.cloudfront.net (CloudFront)',
    'x-amz-cf-pop': 'MAA50-C1',
    'x-amz-cf-id': 'yfDikczTfu3mFWnqolmsgtW_UbEnfWIcTUHgve_f52inwFnNNl3aDw=='
  }
}
✖  Error: Response code 403 (Forbidden)
We apologize for this issue and welcome your bug reports.
Please visit: https://github.com/mongodb-js/version-manager/issues

Try running your command again with debugging on:
   m use --debug

Stack Trace
   HTTPError: Response code 403 (Forbidden)
       at EventEmitter.<anonymous> (/home/xyz/.asdf/installs/nodejs/13.5.0/.npm/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:250:24)
       at EventEmitter.emit (events.js:305:20)
       at Immediate.<anonymous> (/home/xyz/.asdf/installs/nodejs/13.5.0/.npm/lib/node_modules/mongodb-version-manager/node_modules/got/index.js:99:8)
       at processImmediate (internal/timers.js:445:21)

```

**Comment by mattvv** [comment]
+1

**Comment by mohammadfarooqi** [comment]
+1

**Comment by addaleax** [comment]
Hi all! It’s been a long time, but this might be fixed now. Feel free to try again with the latest version here and let me know if it worked.
