### ISSUE TITLE
mongodb-version-manager requires MongoDB to already be installed

### ISSUE THREAD

**Issue by victorhooi** [mongodb-js/version-manager#17]
It seems that mongodb-version-manager requires MongoDB to already be installed (or at least `mongod` to be in the path).

For example, on a fresh OSX box, if I try to install and use MongoDB 2.4.8 - however, I get an error about not found:

```
m 2.4.8
/usr/local/lib/node_modules/mongodb-version-manager/node_modules/which/which.js:80
  throw new Error("not found: "+cmd)
        ^
Error: not found: mongod
    at Function.whichSync (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/which/which.js:80:9)
    at Function.module.exports.current (/usr/local/lib/node_modules/mongodb-version-manager/index.js:115:14)
    at /usr/local/lib/node_modules/mongodb-version-manager/index.js:144:20
    at /usr/local/lib/node_modules/mongodb-version-manager/lib/resolve.js:69:5
    at /usr/local/lib/node_modules/mongodb-version-manager/lib/resolve.js:109:9
    at /usr/local/lib/node_modules/mongodb-version-manager/lib/versions.js:61:7
    at toCallback (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:128:2)
    at /usr/local/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:112:5
    at /usr/local/lib/node_modules/mongodb-version-manager/node_modules/downcache/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)
```

If I then use Homebrew to install MongoDB 3.0.2 (latest version), I'm able to then run mongodb-version-manager.

However, this seems a bit odd, since the whole point of mongodb-version-manager is to download and install MongoDB - is there a reason that it requires MongoDB first before it can work?

**Comment by imlucas** [comment]
Nope that's a straight up bummer bug... Thanks for the report.  Need to get some of our testing up to snuff.

**Comment by imlucas** [comment]
fixed
