### ISSUE TITLE
Should fail gracefully for future (non-existing) versions

### ISSUE THREAD

**Issue by rueckstiess** [mongodb-js/version-manager#18]
```
$ m 3.0.3

/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
                                  ^
RangeError: Invalid array length
    at ProgressBar.render (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:131:35)
    at ProgressBar.tick (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:86:8)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mongodb-version-manager/lib/download.js:44:17)
    at IncomingMessage.emit (events.js:129:20)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

**Comment by imlucas** [comment]
fixed
