### ISSUE TITLE
Error: No available versions?

### ISSUE THREAD

**Issue by joedaimarg** [mongodb-js/version-manager#214]
I'm having a trouble running `m available --stable` 

here's the stack trace: 

     Error: No available versions?
         at /home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/bin/m.js:116:31
         at /home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/index.js:92:5
         at /home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/node_modules/mongodb-version-list/index.js:83:7
         at toCallback (/home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:254:2)
         at /home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/node_modules/downcache/index.js:105:4
         at /home/default/.nvm/versions/node/v18.7.0/lib/node_modules/mongodb-version-manager/node_modules/graceful-fs/graceful-fs.js:123:16
         at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by joedaimarg** [comment]
Looks like the version source is not available anymore. http://dl.mongodb.org/dl/src/.

**Comment by stennie** [comment]
Hi @joedaimarg,

This tool isn't actively maintained -- last release was 2015.

I recommend using `m` instead: https://github.com/aheckmann/m

`m` is a bash script which can also be installed via npm for convenience.

Regards,
Stennie
